import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for Meigen AI. Read the rules and guidelines for using our platform.",
};

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#0c0c0e] text-[#f5f0e8]">
      <div className="max-w-[800px] mx-auto px-6 md:px-12 py-24">
        <Link
          href="/"
          className="inline-block mb-12 text-sm text-[#a09b94] hover:text-[#d4a853] transition-colors"
        >
          ← Back to Home
        </Link>
        <h1 className="font-[family-name:var(--font-display)] text-4xl md:text-5xl font-semibold mb-8">
          Terms of Service
        </h1>
        <p className="text-[#a09b94] mb-12">Last updated: May 12, 2026</p>

        <div className="space-y-10 text-[#a09b94] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Meigen AI (&quot;the Service&quot;), you agree to be
              bound by these Terms of Service. If you do not agree, do not use
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              2. Description of Service
            </h2>
            <p>
              Meigen AI is an AI-powered quote generation and visual card
              creation tool. We provide templates, text generation, and export
              capabilities for personal and commercial use subject to these
              terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              3. User Accounts
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>
                You must provide accurate information when creating an account.
              </li>
              <li>
                You are responsible for maintaining the confidentiality of your
                account credentials.
              </li>
              <li>
                You must be at least 13 years old to use the Service.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              4. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-disc list-inside space-y-2 mt-2">
              <li>
                Use the Service for any illegal purpose or to violate any laws.
              </li>
              <li>
                Generate content that is harmful, threatening, abusive,
                harassing, defamatory, or discriminatory.
              </li>
              <li>
                Attempt to interfere with or disrupt the Service or its
                infrastructure.
              </li>
              <li>
                Resell, redistribute, or scrape the Service or its outputs at
                scale without authorization.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              5. Intellectual Property
            </h2>
            <p>
              <strong className="text-[#f5f0e8]">Your content:</strong> You
              retain ownership of any text, logos, or brand assets you upload.
              You grant us a limited license to use these solely to provide the
              Service.
            </p>
            <p className="mt-2">
              <strong className="text-[#f5f0e8]">AI-generated quotes:</strong>{" "}
              Quotes generated by our AI are provided on an &quot;as-is&quot; basis. We do
              not guarantee originality or uniqueness. You are responsible for
              verifying that generated content does not infringe third-party
              rights before commercial use.
            </p>
            <p className="mt-2">
              <strong className="text-[#f5f0e8]">Templates:</strong> Our
              template designs and software are owned by Meigen AI and licensed
              to you for use within the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              6. Subscriptions and Payments
            </h2>
            <ul className="list-disc list-inside space-y-2">
              <li>
                Pro and Team plans are billed in advance on a monthly or annual
                basis.
              </li>
              <li>
                You may cancel at any time. Cancellation takes effect at the end
                of the current billing period.
              </li>
              <li>
                Refunds: first-time purchases qualify for a 7-day refund if
                you&apos;ve used less than 20% of your monthly quota.
              </li>
              <li>
                We reserve the right to change pricing with 30 days&apos; notice.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              7. Disclaimer of Warranties
            </h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind.
              We do not guarantee that AI-generated quotes are accurate,
              original, or suitable for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              8. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, Meigen AI shall not be
              liable for any indirect, incidental, special, or consequential
              damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              9. Termination
            </h2>
            <p>
              We may suspend or terminate your account if you violate these
              Terms. You may delete your account at any time from your Account
              Settings.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              10. Changes to Terms
            </h2>
            <p>
              We may update these Terms from time to time. We will notify you of
              material changes via email or through the Service. Continued use
              after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">
              11. Contact
            </h2>
            <p>
              For questions about these Terms, email{" "}
              <a
                href="mailto:support@meigenai.org"
                className="text-[#d4a853] hover:underline"
              >
                support@meigenai.org
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
