import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Content Disclaimer for Meigen AI Quotes",
  description:
    "Read the AI content disclaimer for Meigen AI quotes, including review responsibilities, professional advice limits, originality, and third-party rights.",
};

export default function Disclaimer() {
  return (
    <main className="min-h-screen bg-[#0c0c0e] text-[#f5f0e8]">
      <div className="max-w-[800px] mx-auto px-6 md:px-12 py-24">
        <Link href="/" className="inline-block mb-12 text-sm text-[#a09b94] hover:text-[#d4a853] transition-colors">
          ← Back to Home
        </Link>
        <h1 className="font-[family-name:var(--font-display)] text-4xl md:text-5xl font-semibold mb-8">Disclaimer</h1>
        <p className="text-[#a09b94] mb-12">Last updated: May 12, 2026</p>
        <p className="text-[#a09b94] leading-relaxed mb-10">
          This AI content disclaimer explains how to review AI-generated quotes,
          avoid treating generated text as professional advice, and respect
          third-party rights before publishing Meigen AI quote cards. It also
          clarifies that users should check tone, claims, attribution, and legal
          suitability for their own audience before sharing generated material in
          public or commercial channels.
        </p>
        <div className="space-y-10 text-[#a09b94] leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">AI-Generated Content</h2>
            <p>Quotes and text generated by Meigen AI are produced by artificial intelligence. We do not guarantee accuracy, originality, or appropriateness for any specific purpose. You are responsible for reviewing and verifying generated content before publication or commercial use.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">No Professional Advice</h2>
            <p>Content generated through our Service does not constitute legal, financial, medical, or other professional advice.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-[#f5f0e8] mb-4">Third-Party Rights</h2>
            <p>Generated quotes may inadvertently resemble existing works. We are not liable for any claims arising from similarities to third-party content. Users assume full responsibility for ensuring their use does not infringe upon copyrights, trademarks, or other intellectual property rights.</p>
          </section>
        </div>
      </div>
    </main>
  );
}
